trigger:
  - master

pr:
  - master

strategy:
  matrix:
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x
  maxParallel: 2

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      git config --get remote.origin.url
    displayName: "GIT ORIGIN"
